/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Zbots 文档",
  "description": "魔方机器人",
  "base": "/",
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/yuxin.png",
        "actionText": "快速上手 →",
        "actionLink": "/guide/",
        "footer": "沪ICP备18003829号-4 李政",
        "features": [
          {
            "title": "赞助",
            "details": "裕鑫。"
          },
          {
            "title": "QQ交流群号",
            "details": "374735267。"
          },
          {
            "title": "bug反馈",
            "details": "QQ875543533。"
          }
        ]
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-8751a5ac",
      "path": "/"
    },
    {
      "title": "CUBEPIC",
      "frontmatter": {},
      "regularPath": "/guide/cubepic.html",
      "relativePath": "guide/cubepic.md",
      "key": "v-21ddc7e4",
      "path": "/guide/cubepic.html",
      "headers": [
        {
          "level": 2,
          "title": "介绍",
          "slug": "介绍"
        },
        {
          "level": 2,
          "title": "使用方法",
          "slug": "使用方法"
        },
        {
          "level": 3,
          "title": "生成魔方图",
          "slug": "生成魔方图"
        }
      ]
    },
    {
      "title": "介绍",
      "frontmatter": {},
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-2952dc86",
      "path": "/guide/",
      "headers": [
        {
          "level": 2,
          "title": "申请流程",
          "slug": "申请流程"
        },
        {
          "level": 2,
          "title": "使用说明",
          "slug": "使用说明"
        },
        {
          "level": 3,
          "title": "功能",
          "slug": "功能"
        },
        {
          "level": 3,
          "title": "附录",
          "slug": "附录"
        }
      ]
    },
    {
      "title": "CUBER",
      "frontmatter": {},
      "regularPath": "/guide/cuber.html",
      "relativePath": "guide/cuber.md",
      "key": "v-70244f38",
      "path": "/guide/cuber.html",
      "headers": [
        {
          "level": 2,
          "title": "介绍",
          "slug": "介绍"
        },
        {
          "level": 2,
          "title": "使用方法",
          "slug": "使用方法"
        },
        {
          "level": 3,
          "title": "根据名字查询魔友报名的比赛",
          "slug": "根据名字查询魔友报名的比赛"
        }
      ]
    },
    {
      "title": "快递",
      "frontmatter": {},
      "regularPath": "/guide/express.html",
      "relativePath": "guide/express.md",
      "key": "v-94a672f8",
      "path": "/guide/express.html",
      "headers": [
        {
          "level": 2,
          "title": "介绍",
          "slug": "介绍"
        },
        {
          "level": 2,
          "title": "使用方法",
          "slug": "使用方法"
        },
        {
          "level": 3,
          "title": "查询快递",
          "slug": "查询快递"
        }
      ]
    },
    {
      "title": "管理",
      "frontmatter": {},
      "regularPath": "/guide/admin.html",
      "relativePath": "guide/admin.md",
      "key": "v-c4c8bab8",
      "path": "/guide/admin.html",
      "headers": [
        {
          "level": 2,
          "title": "介绍",
          "slug": "介绍"
        },
        {
          "level": 2,
          "title": "使用方法",
          "slug": "使用方法"
        },
        {
          "level": 3,
          "title": "添加管理员",
          "slug": "添加管理员"
        },
        {
          "level": 3,
          "title": "删除管理员",
          "slug": "删除管理员"
        },
        {
          "level": 3,
          "title": "列出管理员",
          "slug": "列出管理员"
        },
        {
          "level": 3,
          "title": "踢人",
          "slug": "踢人"
        },
        {
          "level": 3,
          "title": "踢人(禁止加群)",
          "slug": "踢人-禁止加群"
        },
        {
          "level": 3,
          "title": "禁言",
          "slug": "禁言"
        },
        {
          "level": 3,
          "title": "解除禁言",
          "slug": "解除禁言"
        }
      ]
    },
    {
      "title": "美图",
      "frontmatter": {},
      "regularPath": "/guide/picture.html",
      "relativePath": "guide/picture.md",
      "key": "v-401050c4",
      "path": "/guide/picture.html",
      "headers": [
        {
          "level": 2,
          "title": "介绍",
          "slug": "介绍"
        },
        {
          "level": 2,
          "title": "使用方法",
          "slug": "使用方法"
        },
        {
          "level": 3,
          "title": "获取美图",
          "slug": "获取美图"
        }
      ]
    },
    {
      "title": "BOTML",
      "frontmatter": {},
      "regularPath": "/appendices/botml.html",
      "relativePath": "appendices/botml.md",
      "key": "v-db4b4bd0",
      "path": "/appendices/botml.html",
      "headers": [
        {
          "level": 2,
          "title": "介绍",
          "slug": "介绍"
        },
        {
          "level": 2,
          "title": "常用标签",
          "slug": "常用标签"
        },
        {
          "level": 3,
          "title": "at",
          "slug": "at"
        },
        {
          "level": 3,
          "title": "speech",
          "slug": "speech"
        },
        {
          "level": 3,
          "title": "cubepic",
          "slug": "cubepic"
        },
        {
          "level": 3,
          "title": "next",
          "slug": "next"
        },
        {
          "level": 3,
          "title": "sleep",
          "slug": "sleep"
        }
      ]
    },
    {
      "title": "打乱",
      "frontmatter": {},
      "regularPath": "/guide/scramble.html",
      "relativePath": "guide/scramble.md",
      "key": "v-f3f077e0",
      "path": "/guide/scramble.html",
      "headers": [
        {
          "level": 2,
          "title": "介绍",
          "slug": "介绍"
        },
        {
          "level": 2,
          "title": "指令魔方对应表",
          "slug": "指令魔方对应表"
        },
        {
          "level": 2,
          "title": "使用方法",
          "slug": "使用方法"
        },
        {
          "level": 3,
          "title": "获取2阶魔方打乱",
          "slug": "获取2阶魔方打乱"
        },
        {
          "level": 3,
          "title": "获取3阶魔方打乱",
          "slug": "获取3阶魔方打乱"
        },
        {
          "level": 3,
          "title": "获取4阶魔方打乱",
          "slug": "获取4阶魔方打乱"
        },
        {
          "level": 3,
          "title": "获取5阶魔方打乱",
          "slug": "获取5阶魔方打乱"
        },
        {
          "level": 3,
          "title": "获取金字塔魔方打乱",
          "slug": "获取金字塔魔方打乱"
        },
        {
          "level": 3,
          "title": "获取斜转魔方打乱",
          "slug": "获取斜转魔方打乱"
        },
        {
          "level": 3,
          "title": "获取魔表魔方打乱",
          "slug": "获取魔表魔方打乱"
        },
        {
          "level": 3,
          "title": "获取SQ-1魔方打乱",
          "slug": "获取sq-1魔方打乱"
        }
      ]
    },
    {
      "title": "复读",
      "frontmatter": {},
      "regularPath": "/guide/repeat.html",
      "relativePath": "guide/repeat.md",
      "key": "v-11078874",
      "path": "/guide/repeat.html",
      "headers": [
        {
          "level": 2,
          "title": "介绍",
          "slug": "介绍"
        },
        {
          "level": 2,
          "title": "使用方法",
          "slug": "使用方法"
        },
        {
          "level": 3,
          "title": "自动复读",
          "slug": "自动复读"
        }
      ]
    },
    {
      "title": "学习",
      "frontmatter": {},
      "regularPath": "/guide/learn.html",
      "relativePath": "guide/learn.md",
      "key": "v-cdf1b178",
      "path": "/guide/learn.html",
      "headers": [
        {
          "level": 2,
          "title": "介绍",
          "slug": "介绍"
        },
        {
          "level": 2,
          "title": "特殊含义表",
          "slug": "特殊含义表"
        },
        {
          "level": 2,
          "title": "使用方法",
          "slug": "使用方法"
        },
        {
          "level": 3,
          "title": "新增/修改指令",
          "slug": "新增-修改指令"
        },
        {
          "level": 3,
          "title": "设置指令不回复",
          "slug": "设置指令不回复"
        },
        {
          "level": 3,
          "title": "指令恢复默认",
          "slug": "指令恢复默认"
        },
        {
          "level": 3,
          "title": "清空指令",
          "slug": "清空指令"
        },
        {
          "level": 2,
          "title": "执行顺序说明",
          "slug": "执行顺序说明"
        }
      ]
    },
    {
      "title": "COMP",
      "frontmatter": {},
      "regularPath": "/guide/comp.html",
      "relativePath": "guide/comp.md",
      "key": "v-ec409ae8",
      "path": "/guide/comp.html",
      "headers": [
        {
          "level": 2,
          "title": "介绍",
          "slug": "介绍"
        },
        {
          "level": 2,
          "title": "使用方法",
          "slug": "使用方法"
        },
        {
          "level": 3,
          "title": "查询近期赛事列表",
          "slug": "查询近期赛事列表"
        },
        {
          "level": 3,
          "title": "查询某赛事详细信息",
          "slug": "查询某赛事详细信息"
        },
        {
          "level": 3,
          "title": "查询某赛事详细信息(带地图)",
          "slug": "查询某赛事详细信息-带地图"
        }
      ]
    },
    {
      "title": "开关",
      "frontmatter": {},
      "regularPath": "/guide/switch.html",
      "relativePath": "guide/switch.md",
      "key": "v-0f9092fc",
      "path": "/guide/switch.html",
      "headers": [
        {
          "level": 2,
          "title": "介绍",
          "slug": "介绍"
        },
        {
          "level": 2,
          "title": "使用方法",
          "slug": "使用方法"
        },
        {
          "level": 3,
          "title": "整体启用",
          "slug": "整体启用"
        },
        {
          "level": 3,
          "title": "整体停用",
          "slug": "整体停用"
        },
        {
          "level": 3,
          "title": "启用某功能",
          "slug": "启用某功能"
        },
        {
          "level": 3,
          "title": "停用某功能",
          "slug": "停用某功能"
        }
      ]
    },
    {
      "title": "WCA",
      "frontmatter": {},
      "regularPath": "/guide/wca.html",
      "relativePath": "guide/wca.md",
      "key": "v-4625b2e4",
      "path": "/guide/wca.html",
      "headers": [
        {
          "level": 2,
          "title": "介绍",
          "slug": "介绍"
        },
        {
          "level": 2,
          "title": "使用方法",
          "slug": "使用方法"
        },
        {
          "level": 3,
          "title": "根据WCA ID精确查询",
          "slug": "根据wca-id精确查询"
        },
        {
          "level": 3,
          "title": "根据关键词查询",
          "slug": "根据关键词查询"
        }
      ]
    },
    {
      "title": "欢迎",
      "frontmatter": {},
      "regularPath": "/guide/welcome.html",
      "relativePath": "guide/welcome.md",
      "key": "v-b46de778",
      "path": "/guide/welcome.html",
      "headers": [
        {
          "level": 2,
          "title": "介绍",
          "slug": "介绍"
        },
        {
          "level": 2,
          "title": "特殊含义表",
          "slug": "特殊含义表"
        },
        {
          "level": 2,
          "title": "使用方法",
          "slug": "使用方法"
        },
        {
          "level": 3,
          "title": "设置欢迎",
          "slug": "设置欢迎"
        },
        {
          "level": 3,
          "title": "查看欢迎",
          "slug": "查看欢迎"
        }
      ]
    }
  ],
  "themeConfig": {
    "sidebar": [
      {
        "title": "功能",
        "children": [
          "/guide/switch.md",
          "/guide/scramble.md",
          "/guide/wca.md",
          "/guide/comp.md",
          "/guide/cuber.md",
          "/guide/cubepic.md",
          "/guide/admin.md",
          "/guide/welcome.md",
          "/guide/express.md",
          "/guide/picture.md",
          "/guide/learn.md",
          "/guide/repeat.md"
        ]
      },
      {
        "title": "附录",
        "children": [
          "/appendices/botml.md"
        ]
      }
    ],
    "sidebarDepth": 3
  }
}