/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Zbot 文档",
  "description": "QQ魔方机器人",
  "base": "/",
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "actionText": "快速上手 →",
        "actionLink": "/guide/",
        "footer": "By lz1998",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue 驱动",
            "details": "享受 Vue + webpack 的开发体验，可以在 Markdown 中使用 Vue 组件，又可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 会为每个页面预渲染生成静态的 HTML，同时，每个页面被加载的时候，将作为 SPA 运行。"
          }
        ]
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-8751a5ac",
      "path": "/"
    },
    {
      "title": "WCA",
      "frontmatter": {},
      "regularPath": "/wca/",
      "relativePath": "wca/README.md",
      "key": "v-17fb8e8b",
      "path": "/wca/",
      "headers": [
        {
          "level": 2,
          "title": "使用方法",
          "slug": "使用方法"
        },
        {
          "level": 2,
          "title": "示例",
          "slug": "示例"
        }
      ]
    },
    {
      "title": "开关",
      "frontmatter": {},
      "regularPath": "/switch/",
      "relativePath": "switch/README.md",
      "key": "v-7f9d290d",
      "path": "/switch/",
      "headers": [
        {
          "level": 2,
          "title": "使用方法",
          "slug": "使用方法"
        },
        {
          "level": 2,
          "title": "示例",
          "slug": "示例"
        }
      ]
    },
    {
      "title": "介绍",
      "frontmatter": {},
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-2952dc86",
      "path": "/guide/",
      "headers": [
        {
          "level": 2,
          "title": "申请流程",
          "slug": "申请流程"
        },
        {
          "level": 2,
          "title": "功能",
          "slug": "功能"
        }
      ]
    },
    {
      "title": "打乱",
      "frontmatter": {},
      "regularPath": "/scramble/",
      "relativePath": "scramble/README.md",
      "key": "v-23eb84ad",
      "path": "/scramble/",
      "headers": [
        {
          "level": 2,
          "title": "魔方种类",
          "slug": "魔方种类"
        },
        {
          "level": 2,
          "title": "示例",
          "slug": "示例"
        }
      ]
    }
  ],
  "themeConfig": {
    "sidebar": [
      {
        "title": "目录",
        "children": [
          "/switch/",
          "/scramble/",
          "/wca/"
        ]
      }
    ]
  }
}