/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Zbot 文档",
  "description": "裕鑫赞助",
  "base": "/",
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/yuxin.png",
        "actionText": "快速上手 →",
        "actionLink": "/guide/",
        "footer": "By lz1998",
        "features": [
          {
            "title": "赞助",
            "details": "裕鑫。"
          },
          {
            "title": "QQ交流群号",
            "details": "374735267。"
          },
          {
            "title": "bug反馈",
            "details": "QQ875543533。"
          }
        ]
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-8751a5ac",
      "path": "/"
    },
    {
      "title": "CUBEPIC",
      "frontmatter": {},
      "regularPath": "/cubepic/",
      "relativePath": "cubepic/README.md",
      "key": "v-c4575e6a",
      "path": "/cubepic/",
      "headers": [
        {
          "level": 2,
          "title": "介绍",
          "slug": "介绍"
        },
        {
          "level": 2,
          "title": "使用方法",
          "slug": "使用方法"
        },
        {
          "level": 3,
          "title": "生成魔方图",
          "slug": "生成魔方图"
        }
      ]
    },
    {
      "title": "CUBER",
      "frontmatter": {},
      "regularPath": "/cuber/",
      "relativePath": "cuber/README.md",
      "key": "v-3e0f1c3b",
      "path": "/cuber/",
      "headers": [
        {
          "level": 2,
          "title": "介绍",
          "slug": "介绍"
        },
        {
          "level": 2,
          "title": "使用方法",
          "slug": "使用方法"
        },
        {
          "level": 3,
          "title": "根据名字查询魔友报名的比赛",
          "slug": "根据名字查询魔友报名的比赛"
        }
      ]
    },
    {
      "title": "管理",
      "frontmatter": {},
      "regularPath": "/admin/",
      "relativePath": "admin/README.md",
      "key": "v-6edd5bd7",
      "path": "/admin/",
      "headers": [
        {
          "level": 2,
          "title": "介绍",
          "slug": "介绍"
        },
        {
          "level": 2,
          "title": "使用方法",
          "slug": "使用方法"
        },
        {
          "level": 3,
          "title": "添加管理员",
          "slug": "添加管理员"
        },
        {
          "level": 3,
          "title": "删除管理员",
          "slug": "删除管理员"
        },
        {
          "level": 3,
          "title": "列出管理员",
          "slug": "列出管理员"
        },
        {
          "level": 3,
          "title": "踢人",
          "slug": "踢人"
        },
        {
          "level": 3,
          "title": "踢人(禁止加群)",
          "slug": "踢人-禁止加群"
        },
        {
          "level": 3,
          "title": "禁言",
          "slug": "禁言"
        },
        {
          "level": 3,
          "title": "解除禁言",
          "slug": "解除禁言"
        }
      ]
    },
    {
      "title": "打乱",
      "frontmatter": {},
      "regularPath": "/scramble/",
      "relativePath": "scramble/README.md",
      "key": "v-23eb84ad",
      "path": "/scramble/",
      "headers": [
        {
          "level": 2,
          "title": "介绍",
          "slug": "介绍"
        },
        {
          "level": 2,
          "title": "使用方法",
          "slug": "使用方法"
        },
        {
          "level": 3,
          "title": "获取2阶魔方打乱",
          "slug": "获取2阶魔方打乱"
        },
        {
          "level": 3,
          "title": "获取3阶魔方打乱",
          "slug": "获取3阶魔方打乱"
        },
        {
          "level": 3,
          "title": "获取4阶魔方打乱",
          "slug": "获取4阶魔方打乱"
        },
        {
          "level": 3,
          "title": "获取5阶魔方打乱",
          "slug": "获取5阶魔方打乱"
        },
        {
          "level": 3,
          "title": "获取金字塔魔方打乱",
          "slug": "获取金字塔魔方打乱"
        },
        {
          "level": 3,
          "title": "获取斜转魔方打乱",
          "slug": "获取斜转魔方打乱"
        },
        {
          "level": 3,
          "title": "获取魔表魔方打乱",
          "slug": "获取魔表魔方打乱"
        },
        {
          "level": 3,
          "title": "获取SQ-1魔方打乱",
          "slug": "获取sq-1魔方打乱"
        }
      ]
    },
    {
      "title": "介绍",
      "frontmatter": {},
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-2952dc86",
      "path": "/guide/",
      "headers": [
        {
          "level": 2,
          "title": "申请流程",
          "slug": "申请流程"
        },
        {
          "level": 2,
          "title": "功能",
          "slug": "功能"
        }
      ]
    },
    {
      "title": "COMP",
      "frontmatter": {},
      "regularPath": "/comp/",
      "relativePath": "comp/README.md",
      "key": "v-29f2df6d",
      "path": "/comp/",
      "headers": [
        {
          "level": 2,
          "title": "介绍",
          "slug": "介绍"
        },
        {
          "level": 2,
          "title": "使用方法",
          "slug": "使用方法"
        },
        {
          "level": 3,
          "title": "查询近期赛事列表",
          "slug": "查询近期赛事列表"
        },
        {
          "level": 3,
          "title": "查询某赛事详细信息",
          "slug": "查询某赛事详细信息"
        }
      ]
    },
    {
      "title": "欢迎",
      "frontmatter": {},
      "regularPath": "/welcome/",
      "relativePath": "welcome/README.md",
      "key": "v-1ebfd8f1",
      "path": "/welcome/",
      "headers": [
        {
          "level": 2,
          "title": "介绍",
          "slug": "介绍"
        },
        {
          "level": 2,
          "title": "使用方法",
          "slug": "使用方法"
        },
        {
          "level": 3,
          "title": "设置欢迎语",
          "slug": "设置欢迎语"
        },
        {
          "level": 2,
          "title": "特殊含义",
          "slug": "特殊含义"
        }
      ]
    },
    {
      "title": "WCA",
      "frontmatter": {},
      "regularPath": "/wca/",
      "relativePath": "wca/README.md",
      "key": "v-17fb8e8b",
      "path": "/wca/",
      "headers": [
        {
          "level": 2,
          "title": "介绍",
          "slug": "介绍"
        },
        {
          "level": 2,
          "title": "使用方法",
          "slug": "使用方法"
        },
        {
          "level": 3,
          "title": "根据WCA ID精确查询",
          "slug": "根据wca-id精确查询"
        },
        {
          "level": 3,
          "title": "根据关键词查询",
          "slug": "根据关键词查询"
        }
      ]
    },
    {
      "title": "开关",
      "frontmatter": {},
      "regularPath": "/switch/",
      "relativePath": "switch/README.md",
      "key": "v-7f9d290d",
      "path": "/switch/",
      "headers": [
        {
          "level": 2,
          "title": "介绍",
          "slug": "介绍"
        },
        {
          "level": 2,
          "title": "使用方法",
          "slug": "使用方法"
        },
        {
          "level": 3,
          "title": "整体启用",
          "slug": "整体启用"
        },
        {
          "level": 3,
          "title": "整体停用",
          "slug": "整体停用"
        },
        {
          "level": 3,
          "title": "启用某功能",
          "slug": "启用某功能"
        },
        {
          "level": 3,
          "title": "停用某功能",
          "slug": "停用某功能"
        }
      ]
    }
  ],
  "themeConfig": {
    "sidebar": [
      {
        "title": "目录",
        "children": [
          "/switch/",
          "/scramble/",
          "/wca/",
          "/comp/",
          "/cuber/",
          "/cubepic/",
          "/admin/",
          "/welcome/"
        ]
      }
    ],
    "sidebarDepth": 3
  }
}